In [219]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [220]:
X , y = load_diabetes(return_X_y = True)

In [221]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [222]:
from sklearn.model_selection import train_test_split

In [223]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2)

In [224]:
class SGD:
    def __init__(self , learning_rate , epochs):
        self.lr = learning_rate
        self.epochs = epochs
        self.coef_ = None
        self.intercept_ = None

    def fit(self , X_train , y_train):
        self.coef_ = np.ones(X_train.shape[1])
        self.intercept_ = 0
        for i in range(self.epochs):
            for 
            idx = np.random.randint(0 , X_train.shape[0])
            y_hat = np.dot(X_train[idx] , self.coef_) + self.intercept_
            intercept_derv = -2 * (y_train[idx] - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_derv)

            coef_derv = -2 * (y_train[idx] - y_hat) * X_train[idx]
            self.coef_  = self.coef_ - (self.lr * coef_derv)
        print(self.coef_)
        print(self.intercept_)
    def predict(self , X_test):
        return np.dot(X_test , self.coef_) + self.intercept_
            

In [225]:
reg = SGD(learning_rate = 0.1 , epochs = 1000)

In [226]:
reg.fit(X_train , y_train)

[  71.71224738  -44.72934474  249.25478169  191.14151301   51.87761087
   33.27020374 -131.61861132  134.28198793  204.56724792  130.26348315]
171.49075413965525


In [227]:
y_pred = reg.predict(X_test)

In [228]:
from sklearn.metrics import mean_squared_error , r2_score

In [229]:
mean_squared_error(y_test, y_pred)
r2_score(y_test , y_pred)

0.4171294913430359

In [230]:
from sklearn.linear_model import SGDRegressor

In [231]:
sgd = SGDRegressor(
    learning_rate='constant',
    eta0=0.1,
    max_iter=1000,
    shuffle=False,
    tol=None,
    random_state=42
)

In [232]:
sgd.fit(X_train , y_train)

SGDRegressor(eta0=0.1, learning_rate='constant', random_state=42, shuffle=False,
             tol=None)

In [233]:
sgd.coef_

array([  25.06581456, -255.70508537,  515.77173792,  304.60021539,
       -142.74062809,    8.98151624, -185.23504658,   80.46698276,
        457.30240533,   90.91530692])

In [234]:
sgd.intercept_

array([176.54973181])

In [235]:
y_pred2 = sgd.predict(X_test)

In [236]:
r2_score(y_test , y_pred2)

0.48964582644567767